import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { LifeAdminItem } from '../types/document';

export interface PDFReportOptions {
  items: LifeAdminItem[];
  userEmail?: string;
  userName?: string;
  title?: string;
  notes?: string;
}

export function generateVaultPdfReport(options: PDFReportOptions): void {
  const { items, userEmail, userName, title = 'OmniVault Pro - Vault Summary Report', notes } = options;

  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Primary Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 70, 'F');

  // Accent Line
  doc.setFillColor(16, 185, 129); // emerald-500
  doc.rect(0, 68, pageWidth, 4, 'F');

  // Title & Subtitle
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text('OMNIVAULT PRO', 40, 36);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text('Smart Life-Admin, Document & Milestone Intelligence Engine', 40, 52);

  // Meta info on top right
  doc.setFontSize(9);
  doc.setTextColor(203, 213, 225); // slate-300
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
  doc.text(`Generated: ${dateStr}`, pageWidth - 40, 32, { align: 'right' });
  if (userEmail) {
    doc.text(`Account: ${userEmail}`, pageWidth - 40, 46, { align: 'right' });
  }

  // Section Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text(title, 40, 95);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Total Selected Records: ${items.length} | Hard Copy Backup & Family Emergency Dossier`,
    40,
    110
  );

  // Table Columns & Data
  const tableData = items.map((item, index) => {
    const days = item.countdown_calculations?.days_remaining_countdown;
    const daysStr = days !== null && days !== undefined ? `${days} days` : 'N/A';
    const amountStr = item.financial_details?.total_amount_due || '—';
    const primaryId = item.identification_numbers?.primary_id || '—';
    const dueDate = item.important_dates?.expiry_date_or_due_date || '—';

    return [
      String(index + 1),
      item.document_or_event_name,
      item.category,
      item.holder_or_person_name || '—',
      primaryId,
      dueDate,
      amountStr,
      `${item.countdown_calculations?.status_flag || 'Active'} (${daysStr})`,
      item.action_required || 'None',
    ];
  });

  autoTable(doc, {
    startY: 125,
    margin: { left: 40, right: 40, bottom: 40 },
    head: [[
      '#',
      'Document / Event',
      'Category',
      'Person / Holder',
      'Identifier / ID',
      'Due / Expiry',
      'Amount Due',
      'Status',
      'Action Required',
    ]],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59], // slate-800
      textColor: [255, 255, 255],
      fontSize: 8.5,
      fontStyle: 'bold',
      halign: 'left',
    },
    styles: {
      fontSize: 8,
      cellPadding: 6,
      textColor: [30, 41, 59],
      lineColor: [226, 232, 240], // slate-200
      lineWidth: 0.5,
      overflow: 'linebreak',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // slate-50
    },
    columnStyles: {
      0: { cellWidth: 24, halign: 'center' },
      1: { cellWidth: 120, fontStyle: 'bold' },
      2: { cellWidth: 80 },
      3: { cellWidth: 85 },
      4: { cellWidth: 80, font: 'courier' },
      5: { cellWidth: 70 },
      6: { cellWidth: 75, fontStyle: 'bold' },
      7: { cellWidth: 90 },
      8: { cellWidth: 85 },
    },
  });

  // Footer note on last page
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      'Confidential • Generated by OmniVault Pro • Keep in a safe, fireproof document folder.',
      40,
      pageHeight - 20
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 40, pageHeight - 20, { align: 'right' });
  }

  const safeDate = new Date().toISOString().slice(0, 10);
  doc.save(`OmniVault_Vault_Summary_${safeDate}.pdf`);
}
